[package]
name = "rmenu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/m0anifest.html

[dependencies]
redargs = { path = "../redargs" }
x11rb =  { version = "0.8.1", features = ["all-extensions"] }
